# Change these first
owner: verificador-precios # Your GitHub organization or username, where this repository lives
repo: la-bodega-china-upptime-2 # The name of this repository

sites:
  - name: Integración empresarial
    url: https://www.prueba.xadanimx.com/api/search-by-codebar-la-bodega-china/M1058-1F-3
    icon: https://labodegachina.com/cdn/shop/files/Favicon-Bodega-China_32x32.png?v=1712133339
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /la-bodega-china-upptime-2 # where "repo" is your repository name
  name: Monitoreo de la disponibilidad del servicio
  logoUrl: https://res.cloudinary.com/xadani-mexico/image/upload/assets/logos/xadani/logo-xadani-b.svg
  introTitle: "**Upptime** is the uptime monitor and status page, powered by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from GitHub repository.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

